# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1315, 685)
        Form.setStyleSheet("QGroupBox{\n"
"    background:#EDF1F4\n"
"}")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1311, 701))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(400, 400))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"font-weight:500;\n"
"color:#19232D;\n"
"border:none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 541, 691))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(62)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 521, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(126)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 410, 521, 261))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(1150, 0, 161, 701))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    background:#2D3D4D;\n"
"    color:white;\n"
"}\n"
"QLabel{\n"
"    color:white\n"
"}\n"
"QPushButton{\n"
"    background:#4471C6;\n"
"    color:white;\n"
"}\n"
"QRadioButton{\n"
"    color:white;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(60, 60, 51, 411))
        self.label.setObjectName("label")
        self.Getback = QtWidgets.QPushButton(self.groupBox_3)
        self.Getback.setGeometry(QtCore.QRect(20, 570, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Getback.setFont(font)
        self.Getback.setStyleSheet("")
        self.Getback.setObjectName("Getback")
        self.Getback_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Getback_2.setGeometry(QtCore.QRect(20, 630, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Getback_2.setFont(font)
        self.Getback_2.setStyleSheet("")
        self.Getback_2.setObjectName("Getback_2")
        self.photoshow = QtWidgets.QGroupBox(self.groupBox_2)
        self.photoshow.setGeometry(QtCore.QRect(550, 20, 571, 651))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(62)
        self.photoshow.setFont(font)
        self.photoshow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.photoshow.setStyleSheet("")
        self.photoshow.setObjectName("photoshow")
        self.readlabel = QtWidgets.QLabel(self.photoshow)
        self.readlabel.setGeometry(QtCore.QRect(30, 40, 541, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readlabel.sizePolicy().hasHeightForWidth())
        self.readlabel.setSizePolicy(sizePolicy)
        self.readlabel.setObjectName("readlabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据统计界面"))
        self.groupBox.setTitle(_translate("Form", "显示记录"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "行人总数"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "高风险人数"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "状态显示"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">数</span></p><p><span style=\" font-size:26pt; font-weight:600;\">据</span></p><p><span style=\" font-size:26pt; font-weight:600;\">库</span></p><p><span style=\" font-size:26pt; font-weight:600;\">查</span></p><p><span style=\" font-size:26pt; font-weight:600;\">询</span></p><p><span style=\" font-size:26pt; font-weight:600;\">界</span></p><p><span style=\" font-size:26pt; font-weight:600;\">面</span></p></body></html>"))
        self.Getback.setText(_translate("Form", "返回"))
        self.Getback_2.setText(_translate("Form", "退出"))
        self.photoshow.setTitle(_translate("Form", "图片记录"))
        self.readlabel.setText(_translate("Form", "图片显示框"))
